################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
FREERTOS \
FREERTOS/portable/GCC/ARM_CM4F \
FREERTOS/portable \
LVGL/demos/benchmark/assets \
LVGL/demos/benchmark \
LVGL/demos/flex_layout \
LVGL/demos/keypad_encoder \
LVGL/demos \
LVGL/demos/multilang/assets/avatars \
LVGL/demos/multilang/assets/emojis \
LVGL/demos/multilang/assets/fonts \
LVGL/demos/multilang/assets \
LVGL/demos/multilang \
LVGL/demos/music/assets \
LVGL/demos/music \
LVGL/demos/render/assets \
LVGL/demos/render \
LVGL/demos/scroll \
LVGL/demos/stress \
LVGL/demos/transform/assets \
LVGL/demos/transform \
LVGL/demos/vector_graphic/assets \
LVGL/demos/vector_graphic \
LVGL/demos/widgets/assets \
LVGL/demos/widgets \
LVGL/examples/anim \
LVGL/examples/assets \
LVGL/examples/assets/emoji \
LVGL/examples/event \
LVGL/examples/get_started \
LVGL/examples/layouts/flex \
LVGL/examples/layouts/grid \
LVGL/examples/libs/barcode \
LVGL/examples/libs/bmp \
LVGL/examples/libs/ffmpeg \
LVGL/examples/libs/freetype \
LVGL/examples/libs/gif \
LVGL/examples/libs/libjpeg_turbo \
LVGL/examples/libs/libpng \
LVGL/examples/libs/lodepng \
LVGL/examples/libs/qrcode \
LVGL/examples/libs/rlottie \
LVGL/examples/libs/tiny_ttf \
LVGL/examples/libs/tjpgd \
LVGL/examples/others/file_explorer \
LVGL/examples/others/fragment \
LVGL/examples/others/gridnav \
LVGL/examples/others/ime \
LVGL/examples/others/imgfont \
LVGL/examples/others/monkey \
LVGL/examples/others/observer \
LVGL/examples/others/snapshot \
LVGL/examples/porting \
LVGL/examples/scroll \
LVGL/examples/styles \
LVGL/examples/widgets/animimg \
LVGL/examples/widgets/arc \
LVGL/examples/widgets/bar \
LVGL/examples/widgets/button \
LVGL/examples/widgets/buttonmatrix \
LVGL/examples/widgets/calendar \
LVGL/examples/widgets/canvas \
LVGL/examples/widgets/chart \
LVGL/examples/widgets/checkbox \
LVGL/examples/widgets/dropdown \
LVGL/examples/widgets/image \
LVGL/examples/widgets/imagebutton \
LVGL/examples/widgets/keyboard \
LVGL/examples/widgets/label \
LVGL/examples/widgets/led \
LVGL/examples/widgets/line \
LVGL/examples/widgets/list \
LVGL/examples/widgets/menu \
LVGL/examples/widgets/msgbox \
LVGL/examples/widgets/obj \
LVGL/examples/widgets/roller \
LVGL/examples/widgets/scale \
LVGL/examples/widgets/slider \
LVGL/examples/widgets/span \
LVGL/examples/widgets/spinbox \
LVGL/examples/widgets/spinner \
LVGL/examples/widgets/switch \
LVGL/examples/widgets/table \
LVGL/examples/widgets/tabview \
LVGL/examples/widgets/textarea \
LVGL/examples/widgets/tileview \
LVGL/examples/widgets/win \
LVGL/src/core \
LVGL/src/display \
LVGL/src/draw \
LVGL/src/draw/nxp/pxp \
LVGL/src/draw/nxp/vglite \
LVGL/src/draw/renesas/dave2d \
LVGL/src/draw/sdl \
LVGL/src/draw/sw/blend \
LVGL/src/draw/sw/blend/neon \
LVGL/src/draw/sw \
LVGL/src/draw/vg_lite \
LVGL/src/drivers/display/drm \
LVGL/src/drivers/display/fb \
LVGL/src/drivers/display/ili9341 \
LVGL/src/drivers/display/lcd \
LVGL/src/drivers/display/st7735 \
LVGL/src/drivers/display/st7789 \
LVGL/src/drivers/display/st7796 \
LVGL/src/drivers/evdev \
LVGL/src/drivers/nuttx \
LVGL/src/drivers/sdl \
LVGL/src/drivers/windows \
LVGL/src/drivers/x11 \
LVGL/src/font \
LVGL/src/indev \
LVGL/src/layouts/flex \
LVGL/src/layouts/grid \
LVGL/src/layouts \
LVGL/src/libs/barcode \
LVGL/src/libs/bin_decoder \
LVGL/src/libs/bmp \
LVGL/src/libs/ffmpeg \
LVGL/src/libs/freetype \
LVGL/src/libs/fsdrv \
LVGL/src/libs/gif \
LVGL/src/libs/libjpeg_turbo \
LVGL/src/libs/libpng \
LVGL/src/libs/lodepng \
LVGL/src/libs/lz4 \
LVGL/src/libs/qrcode \
LVGL/src/libs/rle \
LVGL/src/libs/rlottie \
LVGL/src/libs/tiny_ttf \
LVGL/src/libs/tjpgd \
LVGL/src \
LVGL/src/misc/cache \
LVGL/src/misc \
LVGL/src/osal \
LVGL/src/others/file_explorer \
LVGL/src/others/fragment \
LVGL/src/others/gridnav \
LVGL/src/others/ime \
LVGL/src/others/imgfont \
LVGL/src/others/monkey \
LVGL/src/others/observer \
LVGL/src/others/snapshot \
LVGL/src/others/sysmon \
LVGL/src/others/vg_lite_tvg \
LVGL/src/stdlib/builtin \
LVGL/src/stdlib/clib \
LVGL/src/stdlib \
LVGL/src/stdlib/micropython \
LVGL/src/stdlib/rtthread \
LVGL/src/themes/default \
LVGL/src/themes \
LVGL/src/themes/mono \
LVGL/src/themes/simple \
LVGL/src/tick \
LVGL/src/widgets/animimage \
LVGL/src/widgets/arc \
LVGL/src/widgets/bar \
LVGL/src/widgets/button \
LVGL/src/widgets/buttonmatrix \
LVGL/src/widgets/calendar \
LVGL/src/widgets/canvas \
LVGL/src/widgets/chart \
LVGL/src/widgets/checkbox \
LVGL/src/widgets/dropdown \
LVGL/src/widgets/image \
LVGL/src/widgets/imagebutton \
LVGL/src/widgets/keyboard \
LVGL/src/widgets/label \
LVGL/src/widgets/led \
LVGL/src/widgets/line \
LVGL/src/widgets/list \
LVGL/src/widgets/menu \
LVGL/src/widgets/msgbox \
LVGL/src/widgets/objx_templ \
LVGL/src/widgets/roller \
LVGL/src/widgets/scale \
LVGL/src/widgets/slider \
LVGL/src/widgets/span \
LVGL/src/widgets/spinbox \
LVGL/src/widgets/spinner \
LVGL/src/widgets/switch \
LVGL/src/widgets/table \
LVGL/src/widgets/tabview \
LVGL/src/widgets/textarea \
LVGL/src/widgets/tileview \
LVGL/src/widgets/win \

